const Strings = {

  appName:'STAFFA',
  
  GENDER: [
    {name:"MALE"},
    {name:"FEMALE"}
  ],

  DOC_TYPE: [
    {name:"Passport"},
    {name:"Driving Licence"},
    {name:"Government ID Card"}
  ],

  DISTANCE_MILES: [
    {name:"5 Miles"},
    {name:"10 Miles"},
    {name:"15 Miles"},
    {name:"20 Miles"},
    {name:"25 Miles"},
    {name:"30 Miles"},
    {name:"35 Miles"},
    {name:"40 Miles"},
    {name:"45 Miles"},
    {name:"50 Miles"},
    {name:"55 Miles"},
    {name:"60 Miles"},
    {name:"65 Miles"},
    {name:"70 Miles"},
    {name:"75 Miles"},
    {name:"80 Miles"},
    {name:"85 Miles"},
    {name:"90 Miles"},
    {name:"95 Miles"},
    {name:"100 Miles"}
  ],

  APP_SCREEN_SPLASH:"SplashScreen",
  APP_SCREEN_LOGIN:"LoginScreen",
  APP_SCREEN_SIGNUP:"SignUpScreen",
  APP_SCREEN_FORGOT_PASSWORD:"ForgotPasswordScreen",
  APP_SCREEN_HOME:"HomeScreen",
  APP_SCREEN_VERIFY:"VerifyMobileNumberScreen",
  APP_SCREEN_TNC:"TermsConditionScreen",

  registerNotificationMsg:'We need to notify you of compliance related matters, payments and offers relating to your vocation and aspirations. \n\n You can change this settings at any time in your device settings.',
  registerVerificationMsg:'We need to verify your identity using your government issued identification documentation.',

  PREF_USER_DATA : "UserData",

  FS_FILE_DIR_VERIFICATION:"VerificationDoc",
  FS_FILE_DIR_DBS:"DBS_Doc",
  FS_FILE_DIR_QUALIfICATION:"Qualification",
  FS_FILE_DIR_REFERENCES:"References",
  FS_FILE_DIR_PROFILE:"Profile",

  FS_COLLECTION_USERS : "Users",
  FS_COLLECTION_REGISTER_USET_DATA : "registerData",

  UPDATE_DATA_STATE_LOGIN : "-1",
UPDATE_DATA_STATE_FIRST : "0",
UPDATE_DATA_STATE_SECOND : "1",
UPDATE_DATA_STATE_THIRD : "2",
UPDATE_DATA_STATE_FOUR : "3",
UPDATE_DATA_STATE_FINISH : "4",

// allData:  [{time:"Open: 1 day",title: 'Michael Johnson', desc: 'Review past consult and get advice or\ntreatment from trusted medical clinicians', icon:require('../../res/images/home/user.png')},
// {time:"Upcoming",title: 'Ben Lee', desc: 'Ask a free, anonymous question to our\nclinician network or review past questions', icon:require('../../res/images/home/user.png')},
// {time:"Upcoming",title: 'Mary McKinley', desc: 'Find a doctor-curated plan to meet your health\ngoals or complete ongoing tasks', icon:require('../../res/images/home/user.png')},
// {time:"Upcoming",title: 'Jane Smith', desc: 'Explore answers, tips, and doctor-curated\nmedical information', icon:require('../../res/images/home/user.png')},
// {time:"Upcoming",title: 'Michael Johnson', desc: 'Check your symptoms with our doctor-trained\nartificial intelligence', icon:require('../../res/images/home/user.png')},
// {time:"Upcoming",title: 'Ben Lee', desc: 'Connect with your healthap clinicians or find\na new one', icon:require('../../res/images/home/user.png')},
// {time:"Upcoming",title: 'Add Person', desc: 'Manage the people that you care for', icon:require('../../res/images/home/add_color.png')},
// ],

// myAllData:  [{time:"Open: 1 day",title: 'Michael Johnson', desc: 'Review past consult and get advice or\ntreatment from trusted medical clinicians', icon:require('../../res/images/home/user.png')},
// {time:"Upcoming",title: 'Ben Lee', desc: 'Ask a free, anonymous question to our\nclinician network or review past questions', icon:require('../../res/images/home/user.png')},
// {time:"Upcoming",title: 'Mary McKinley', desc: 'Find a doctor-curated plan to meet your health\ngoals or complete ongoing tasks', icon:require('../../res/images/home/user.png')},
// {time:"Upcoming",title: 'Jane Smith', desc: 'Explore answers, tips, and doctor-curated\nmedical information', icon:require('../../res/images/home/user.png')},
// {time:"Upcoming",title: 'Michael Johnson', desc: 'Check your symptoms with our doctor-trained\nartificial intelligence', icon:require('../../res/images/home/user.png')},
// {time:"Upcoming",title: 'Ben Lee', desc: 'Connect with your healthap clinicians or find\na new one', icon:require('../../res/images/home/user.png')},
// {time:"Upcoming",title: 'Add Person', desc: 'Manage the people that you care for', icon:require('../../res/images/home/add_color.png')},
// ],
  moneyTransferToLabel:"Transfer To:",

  alertLogout:'Are you sure you want to Logout?',
  alertAddProfileData:"Please update your profile and enjoy your first free money transfer",
  alertDeleteProfileMsg:"Are you sure you want to delete photo?",
  alertNoFingerPrintAdded:"No finger print added in your device. Go to Settings -> Security -> Fingerprint and register atleast one fingerprint",

  hintMobileEmail:"Mobile Number OR Email",
  hintConfirmationCode:"Confirmation Code",

  welcomeMessage:"Welcome to Ogleji Transporter Services!\nEnter your mobile number to continue",
  welcomeMessageSignUp:"Welcome to Ogleji Transporter Services!",
  forgotPasswordScreenMessage:"Enter your registered email or username. We will send you link via registered email to reset your password ",
  splashMessage:"Send, Receive, Pay, Save Cash Instantly!",
  msgVerifyOTP:"Please enter the code sent to ",
  msgAddFund:"Please add fund to your account",
  msgMicroloanAmount:"Loan amount should not be greater than",
  msgSomethingWentWrong:'Something went wrong. Please try again',
  msgMaxTransactionLimitExceed:'Maximum transaction limit exceeded',
  msgMaxTransactionAmount:'Maximum amount per transaction is ',
  msgAppUpdate:'Update is available on Play Store. Please update your app',

  fingerPrintEventName:'fingerPrintResult',  
  QuickPayEventName:'QuickPay',  
  QuickPayTransactionEventName:'QuickPayTransaction',  


  prefUserCookie:"UserCookie",
  prefProfileData:"ProfileData",
  prefCurrentDataState:"CurrentDataState",
  prefLoginID:"SIPLoginID",
  prefUserEmail:"UserEmail",
  prefUserName:"UserName",
  prefSIPPassword:"SIPPassword",
  // prefUserCurrency:"UserCurrency",
  // prefUserCountry:"UserCountry",
  // prefUserCountryCode:"UserCountryCode",
  // prefContactUploadTimeStamp:"ContactUploadTimeStamp",
  // prefBaseURL:"BASE_URL",
  // prefUserBalance:"UserBalance",
  // prefUserPIN:'UserPIN',
  // prefIsFirstTime:'isFirstTime',
  // prefTransferLimit:'TransferLimit',
  // prefCurrencyCode:'CurrencyCode',

  prefPrivacyStatus:'prefPrivacyStatus',
  prefPushNotificationStatus:'prefPushNotificationStatus',
  prefSecurityLockStatus:'prefSecurityLockStatus',
  prefFingerPrintEnable:"prefFingerPrintEnable",

  keyABC:"ABC",
  keyBack:"Back",

  dialogButtonOK:"OK",
  dialogButtonCancel:"CANCEL",

  GET_CASH_LIMIT_TYPE_ADD_FUNDS:'add_funds',
  GET_CASH_LIMIT_TYPE_CASH_OUT:'cash_out',
  GET_CASH_LIMIT_TYPE_TRANSFER:'internal_transfer',
  GET_CASH_LIMIT_TYPE_MAX:'max_transaction_amount',

  settingsPushNotifications:"Push Notifications",
    settingsPushNotificationsDesc:"Turn On to receive m-naira notifications",
    settingsPrivacy:"Privacy",
    settingsPrivacyDesc:"Allow others to pay me at m-naira ID",
    settingsSecurityLock:"Security Lock",
    settingsSecurityLockDesc:"Required fingerprint lock or m-naira pin ID to transfer funds",
    settingsChangemNairaPin:"Change m-naira pin",
    settingsPendingPaymentRequest:"Payment Request",
    signOut:"Sign Out",
    settingsEnableFingerPrint:'Fingerprint/PIN Authentication',
    settingsAgentRequest:'Agent Location Request',
    confirmSignOut :"Are you sure you want to logout?",

    
BG_COLOR: [
        'red',
        'blue',
        'yellow',
    ],
ACTIVITY_DATA_PENDING :[
      {name:"Elly",for:"Dinner",amount:"5"}
],
ACTIVITY_DATA_TRANSACTIONS :[
  {name:"Elliena",for:"For my wife support",amount:"55"},
  {name:"Moses",for:"Master Card Debit 1678",amount:"200"},
  {name:"Oglaza",for:"For last night party",amount:"60"},
  {name:"Noel",for:"For Lunch",amount:"100"},
  {name:"Jones",for:"For Dinner",amount:"89"},
  {name:"Nick",for:"Master Card Debit 1678",amount:"250"},
  {name:"Esther",for:"For weekend trip",amount:"500"},
  {name:"Chris",for:"For Christmas",amount:"1000"},
  {name:"Jimmy",for:"Master Card Debit 1678",amount:"160"},
],
ACTIVITY_DATA_1 :[
    {name:"Elly"},
    {name:"Moses"},
    {name:"Oglaza"},
    {name:"Noel"},
    {name:"Jones"},
    {name:"Nick"},
    {name:"Esther"},
    {name:"Chris"},
    {name:"Jimmy"},
],

GROUPS:[
    {name:"Group 1", members:[{name:"Member 1"},{name:"Member 2"},{name:"Member 3"},{name:"Member 4"}]},
    {name:"Group 2", members:[{name:"Member 5"},{name:"Member 6"},{name:"Member 7"},{name:"Member 8"}]},
    {name:"Group 3", members:[{name:"Member 9"},{name:"Member 10"},{name:"Member 11"},{name:"Member 12"}]},
    {name:"Group 4", members:[{name:"Member 13"},{name:"Member 14"},{name:"Member 15"},{name:"Member 16"}]},
    {name:"Group 5", members:[{name:"Member 17"},{name:"Member 18"},{name:"Member 19"},{name:"Member 20"}]},
],

GROUP_VISIBILITY:[
      {name:"Private"},
      {name:"Public"},
],

GROUP_PAYMENT_FREQUENCY:[
    {name:"Daily"},
    {name:"Weekly"},
    {name:"Bi-Weekly"},
    {name:"Monthly"},
  ],
LUMP_SUM_AMOUNT : [
    {name:"50"},
    {name:"100"},
    {name:"200"},
    {name:"250"},
    {name:"500"},
    {name:"1000"},
    {name:"1500"},
    {name:"2000"},
    {name:"2500"},
    {name:"3000"},
    {name:"3500"},
    {name:"4000"},
    {name:"4500"},
    {name:"5000"},
],
NUMBER_OF_GROUP_MEMBERS:[
  {name:"3"},
  {name:"4"},
  {name:"5"},
  {name:"6"},
  {name:"7"},
  {name:"8"},
  {name:"9"},
  {name:"10"},
  {name:"11"},
],
GENDER: [
         {name:"MALE"},
         {name:"FEMALE"}
],
TOP_UP_PLAN : [
         {name:"20"},
         {name:"50"},
         {name:"100"},
         {name:"200"},
         {name:"500"},
],

PAY_BACK_FREQUENCY : [
      {name:"1 Month"},
      {name:"2 Months"},
      {name:"3 Months"},
      {name:"4 Months"},
      {name:"5 Months"},
      {name:"6 Months"},
],

LOAN_DURATION : [
         {name:"1 Month"},
         {name:"2 Months"},
         {name:"3 Months"},
         {name:"4 Months"},
         {name:"5 Months"},
         {name:"6 Months"},
],

MOBILE_TOP_UP_CODE_MAP : {
    0: 'Transaction successfull',
    101: 'Numbering	plan not recognized: the destination/recipient number was not identified as	to belonging to	any	operators covered by m-naira. Re-check recipient	number and/or escalate the case	to the m-naira Support Team for further investigation',
    104: 'Sender and recipient phone numbers are blacklisted due to	fraudulent	activities',
    105: 'Transaction failed due to	insufficient funds in your account\'s prepaid balance. Please reload balance and try again.',
    200: 'Transaction is cancelled by customer',
    202: 'Transaction is cancelled by m-naira',
    203: 'Transaction is failed due to technical issue.',
    204: 'Transaction refused by the operator because the recipient	phone number is	not	a valid	prepaid	account',
    207: 'Transaction amount limit is exceeded',
    213: 'Transaction refused because it was submitted too	closely	after a	preceding Top-up attempt',
    214: 'Transaction refused by the operator for a	reason that	was	not	specified.\nCommon reasons for these types of failures are:\n1. Recipient number not valid for recharge\n2. Service	outage temporarily faced on	the	operator. Please try again at a later time and/or contact the m-naira support team if the problem persists.',
    215: 'Transaction failed due to	an outage and/or connection	issue with the operator. Please	try	again at a later time and/or contact the m-naira Support Team if the problem persists.',
    216: 'Transaction refused by the operator because the recipient	number has not been	activated',
    217: 'Transaction refused by the operator because the recipient	number is no longer	an	active	account',
    218: 'Transaction timed-out	and	failed	because	of	the	long processing	duration. Please try again at a later time and/or contact the m-naira Support Team if the problem persists',
    219: 'Request failed because the key provided does not exist',
    221: 'Transaction refused and the recipient	number flagged for suspicion of	fraud, due to the number of consecutive	Top-up requests	within a short gap of time.	The	recipient phone	number will	be locked out from receiving any Top-up	for	a certain period of	time, after	which,	the	restriction	will be	automatically released',
    222: 'The recipient	has	been blocked from refill directly by the recipient\'s operator.	It prevents	m-naira system from reloading his account. Recipient must call the operator’s customer service to unblock it.',
    223: 'Transaction failed because the transaction ID	specified in the request was not previously	reserved',
    224: 'Transaction failed because the recipient	number	length	does not match (shorter	or	longer)	the	mobile	number	format	of	the	country',
    230: 'The recipient	reaches	the	maximum	number	of	Top-up	allowable in a certain	gap	of	time',
    231: 'The recipient	reaches	the	maximum	amount (in	USD) of	Top-up	allowable in a certain	gap	of	time',
    232: 'Your account	has	reached	its	maximum	number	of	Top-up	allowable in a certain	gap	of	time',
    233: 'Your account	has	reached	its	maximum	amount	(in	USD) of	Top-up	allowable in a	certain	gap	of	time',
    241: 'Your account	has	reached	its	maximum	amount (in	USD) of Top-up allowable within a day',
    242: 'Your account	has	reached	its	maximum	number	of	Top-up	allowable within a day.',
    243: 'Your account	has	reached	its	maximum	amount (in	USD) of	Top-up	allowable within a week',
    244: 'Your account	has	reached	its	maximum	number	of	Top-up	allowable	within	a	week',
    245: 'Your account	has	reached	its	maximum	amount	(in	USD) of	Top-up	allowable within a	month',
    246: 'Your account	has	reached	its	maximum	number	of	Top-up	allowable	within	a	month',
    251: 'The sender has reached its maximum amount	(in	USD) of	Top-up	allowable within a day',
    252: 'The sender has reached its maximum number	of	Top-up	allowable	within	a	day',
    253: 'The sender has reached its maximum amount	(in	USD) of	Top-up	allowable within a	week',
    254: 'The sender has reached its maximum number	of Top-up allowable	within	a week',
    255: 'The sender has reached its maximum amount	(in	USD) of	Top-up	allowable within a month',
    256: 'The sender has reached its maximum number	of	Top-up allowable within	a day month',
    301: 'Denomination	not	available for this destination.',
    310: 'Transaction failed because the Top-up	is	no	longer	available on the operator\'s offer or on the account', 
    311: 'Transaction failed because the Top-up	is	no	longer	available on the account',
    312: 'Transaction failed because operator have	been blocked explicitely in	customer account',
    320: 'Transaction failed because the Top-amount	request	was	not	within the range of	valid amounts',
    321: 'Transaction failed because the currency specified	is not valid for the account',
    401: 'No transaction was found	with the ID	specified (error returned for trans_info method	requests only)',
    777: 'Transaction failed because there are not enough funds	in	your master	account',
    888: 'Transaction failed because there are not enough funds	in	your sub-account',
    900: 'Transaction failed because some of the required fields in	your Top-up	request	are	missing/empty',
    901: 'Transaction failed because the action	specified in <action> field	of the request	is	not	valid',
    902: 'Transaction failed because the invalid input_currency',
    903: 'Transaction failed because the invalid output_currency',
    904: 'Transaction failed because the invalid input_value',
    905: 'Transaction failed because the invalid start_date',
    906: 'Transaction failed because the invalid stop_date',
    907: 'Transaction ID specified in the <reserved_id>	of	the	Top-up	request	is	not	valid',
    908: 'Transaction failed because the account is	not	configured	to	carry out the requested	action',
    909: 'Transaction failed because the request included an invalid field/parameter',
    919: 'Transaction failed because the request is	missing	a mandatory	field/parameter',
    921: 'Transaction failed because the MD5 hash was not correct. Typically indicates that	the	password is	incorrect',
    922: 'Transaction failed because the request originated	from an	IP that	is not	whitelisted	for	the	account',
    923: 'Request failed because Key or	MD5	values are empty',
    925: 'Request failed because the key value included	in the request was not unique than the previous	key	used',
    926: 'Transaction failed because account is not	active.	Please	contact	your Account Manager',
    995: 'Transaction failed because account not found.	Please	enter and use a	correct	login',
    998: 'Request failed due to	technical issues. Please contact m-naira Support Team for further investigation',
    999: 'Unknown Error. To	be	escalated to the m-naira Support Team for further investigation',
},

CURRENCY_OBJECT : {
  'AED': 'د.إ',
  'AFN': '؋',
  'ALL': 'L',
  'AMD': '֏',
  'ANG': 'ƒ',
  'AOA': 'Kz',
  'ARS': '$',
  'AUD': '$',
  'AWG': 'ƒ',
  'AZN': '₼',
  'BAM': 'KM',
  'BBD': '$',
  'BDT': '৳',
  'BGN': 'лв',
  'BHD': '.د.ب',
  'BIF': 'FBu',
  'BMD': '$',
  'BND': '$',
  'BOB': '$b',
  'BRL': 'R$',
  'BSD': '$',
  'BTC': '฿',
  'BTN': 'Nu.',
  'BWP': 'P',
  'BYR': 'Br',
  'BYN': 'Br',
  'BZD': 'BZ$',
  'CAD': '$',
  'CDF': 'FC',
  'CHF': 'CHF',
  'CLP': '$',
  'CNY': '¥',
  'COP': '$',
  'CRC': '₡',
  'CUC': '$',
  'CUP': '₱',
  'CVE': '$',
  'CZK': 'Kč',
  'DJF': 'Fdj',
  'DKK': 'kr',
  'DOP': 'RD$',
  'DZD': 'دج',
  'EEK': 'kr',
  'EGP': '£',
  'ERN': 'Nfk',
  'ETB': 'Br',
  'ETH': 'Ξ',
  'EUR': '€',
  'FJD': '$',
    'FKP': '£',
    'GBP': '£',
    'GEL': '₾',
    'GGP': '£',
    'GHC': '₵',
    'GHS': 'GH₵',
    'GIP': '£',
    'GMD': 'D',
    'GNF': 'FG',
    'GTQ': 'Q',
    'GYD': '$',
    'HKD': '$',
    'HNL': 'L',
    'HRK': 'kn',
    'HTG': 'G',
    'HUF': 'Ft',
    'IDR': 'Rp',
    'ILS': '₪',
    'IMP': '£',
    'INR': '₹',
    'IQD': 'ع.د',
    'IRR': '﷼',
    'ISK': 'kr',
    'JEP': '£',
    'JMD': 'J$',
    'JOD': 'JD',
    'JPY': '¥',
    'KES': 'KSh',
    'KGS': 'лв',
    'KHR': '៛',
    'KMF': 'CF',
    'KPW': '₩',
    'KRW': '₩',
    'KWD': 'KD',
    'KYD': '$',
    'KZT': 'лв',
    'LAK': '₭',
    'LBP': '£',
    'LKR': '₨',
    'LRD': '$',
    'LSL': 'M',
    'LTC': 'Ł',
    'LTL': 'Lt',
    'LVL': 'Ls',
    'LYD': 'LD',
    'MAD': 'MAD',
    'MDL': 'lei',
    'MGA': 'Ar',
    'MKD': 'ден',
    'MMK': 'K',
    'MNT': '₮',
    'MOP': 'MOP$',
    'MRO': 'UM',
    'MRU': 'UM',
    'MUR': '₨',
    'MVR': 'Rf',
    'MWK': 'MK',
    'MXN': '$',
    'MYR': 'RM',
    'MZN': 'MT',
    'NAD': '$',
    'NGN': '₦',
    'NIO': 'C$',
    'NOK': 'kr',
    'NPR': '₨',
    'NZD': '$',
    'OMR': '﷼',
    'PAB': 'B/.',
    'PEN': 'S/.',
    'PGK': 'K',
    'PHP': '₱',
    'PKR': '₨',
    'PLN': 'zł',
    'PYG': 'Gs',
    'QAR': '﷼',
    'RMB': '￥',
    'RON': 'lei',
    'RSD': 'Дин.',
    'RUB': '₽',
    'RWF': 'R₣',
    'SAR': '﷼',
    'SBD': '$',
    'SCR': '₨',
    'SDG': 'ج.س.',
    'SEK': 'kr',
    'SGD': '$',
    'SHP': '£',
    'SLL': 'Le',
    'SOS': 'S',
    'SRD': '$',
    'SSP': '£',
    'STD': 'Db',
    'STN': 'Db',
    'SVC': '$',
    'SYP': '£',
    'SZL': 'E',
    'THB': '฿',
    'TJS': 'SM',
    'TMT': 'T',
    'TND': 'د.ت',
    'TOP': 'T$',
    'TRL': '₤',
    'TRY': '₺',
    'TTD': 'TT$',
    'TVD': '$',
    'TWD': 'NT$',
    'TZS': 'TSh',
    'UAH': '₴',
    'UGX': 'USh',
    'USD': '$',
    'UYU': '$U',
    'UZS': 'лв',
    'VEF': 'Bs',
    'VND': '₫',
    'VUV': 'VT',
    'WST': 'WS$',
    'XAF': 'FCFA',
    'XBT': 'Ƀ',
    'XCD': '$',
    'XOF': 'CFA',
    'XPF': '₣',
    'YER': '﷼',
    'ZAR': 'R',
    'ZWD': 'Z$'
},
BANK_ACCOUNT_TYPE : [
       {name:"Savings"},
       {name:"Current"},    
       {name:"Others"}
],
CURRENCY : [
    // NGN should be 1st always
    {name:"NGN" , symbol:"₦"},
    // NGN should be 1st always

    {name:"AED" , symbol:"د.إ"},
    {name:"AFN" , symbol:"؋"},
    {name:"ALL" , symbol:"L"},
    {name:"AMD" , symbol:"֏"},
    {name:"ANG" , symbol:"ƒ"},
    {name:"AOA" , symbol:"Kz"},
    {name:"ARS" , symbol:"$"},
    {name:"AUD" , symbol:"$"},
    {name:"AWG" , symbol:"ƒ"},
    {name:"AZN" , symbol:"₼"},
    {name:"BAM" , symbol:"KM"},
    {name:"BBD" , symbol:"$"},
    {name:"BDT" , symbol:"৳"},
    {name:"BGN" , symbol:"лв"},

    {name:"BHD" , symbol:".د.ب"},
    {name:"BIF" , symbol:"FBu"},
    {name:"BMD" , symbol:"$"},
    {name:"BND" , symbol:"$"},
    {name:"BOB" , symbol:"$b"},
    {name:"BRL" , symbol:"R$"},
    {name:"BSD" , symbol:"$"},
    {name:"BTC" , symbol:"฿"},
    {name:"BTN" , symbol:"Nu."},
    {name:"BWP" , symbol:"P"},

    {name:"BYR" , symbol:"Br"},
    {name:"BYN" , symbol:"Br"},
    {name:"BZD" , symbol:"BZ$"},
    {name:"CAD" , symbol:"$"},
    {name:"CDF" , symbol:"FC"},
    {name:"CHF" , symbol:"CHF"},
    {name:"CLP" , symbol:"$"},
    {name:"CNY" , symbol:"¥"},
    {name:"COP" , symbol:"$"},
    {name:"CRC" , symbol:"₡"},
    {name:"CUC" , symbol:"$"},
    {name:"CUP" , symbol:"₱"},
    {name:"CVE" , symbol:"$"},

    {name:"CZK" , symbol:"Kč"},
    {name:"DJF" , symbol:"Fdj"},
    {name:"DKK" , symbol:"kr"},
    {name:"DOP" , symbol:"RD$"},
    {name:"DZD" , symbol:"دج"},
    {name:"EEK" , symbol:"kr"},
    {name:"EGP" , symbol:"£"},
    {name:"ERN" , symbol:"Nfk"},
    {name:"ETB" , symbol:"Br"},
    {name:"ETH" , symbol:"Ξ"},
    {name:"EUR" , symbol:"€"},
    {name:"FJD" , symbol:"$"},

    {name:"USD" , symbol:"$"},
    {name:"EUR" , symbol:"€"},
    {name:"CRC" , symbol:"₡"},
    {name:"GBP" , symbol:"£"},
    {name:"ILS" , symbol:"₪"},
    {name:"INR" , symbol:"₹"},
    {name:"JPY" , symbol:"¥"},
    {name:"KRW" , symbol:"₩"},
    
    {name:"PHP" , symbol:"₱"},
    {name:"PLN" , symbol:"zł"},
    {name:"PYG" , symbol:"₲"},
    {name:"THB" , symbol:"฿"},
    {name:"UAH" , symbol:"₴"},
    {name:"VND" , symbol:"₫"}
  
],
 COUNTRIES : [
      {name:"NIGERIA" , ccode:"234" , iso: "NG", currency:"NGN"},
      {name:"ANDORRA" , ccode:"376" , iso: "AD", currency:"EUR"},
      {name:"UNITED ARAB EMIRATES" , ccode:"971" , iso: "AE", currency:"USD" },
      {name:"AFGHANISTAN" , ccode:"93" , iso: "AF", currency:"NGN"},
      {name:"ANTIGUA AND BARBUDA" , ccode:"1268" , iso: "AG", currency:"USD"},
      {name:"ANGUILLA" , ccode:"1264" , iso: "AI", currency:"USD"},
      {name:"ALBANIA" , ccode:"355" , iso: "AL", currency:"NGN"},
      {name:"ARMENIA" , ccode:"374" , iso: "AM", currency:"NGN"},
      {name:"NETHERLANDS ANTILLES" , ccode:"599" , iso: "AN", currency:"EUR"},
      {name:"ANGOLA" , ccode:"244" , iso: "AO", currency:"NGN"},
      {name:"ANTARCTICA" , ccode:"672" , iso: "AQ", currency:"USD" },
      {name:"ARGENTINA" , ccode:"54" , iso: "AR", currency:"PHP"},
      {name:"AMERICAN SAMOA" , ccode:"1684" , iso: "AS", currency:"USD" },
      {name:"AUSTRIA" , ccode:"43" , iso: "AT", currency:"EUR"},
      {name:"AUSTRALIA" , ccode:"61" , iso: "AU", currency:"USD"},
      {name:"ARUBA" , ccode:"297" , iso: "AW", currency:"NGN"},
      {name:"AZERBAIJAN" , ccode:"994" , iso: "AZ", currency:"NGN"},
      {name:"BOSNIA AND HERZEGOVINA" , ccode:"387" , iso: "BA", currency:"NGN"},
      {name:"BARBADOS" , ccode:"1246" , iso: "BB", currency:"USD"},
      {name:"BANGLADESH" , ccode:"880" , iso: "BD", currency:"NGN"},
      {name:"BELGIUM" , ccode:"32" , iso: "BE", currency:"EUR"},
      {name:"BURKINA FASO" , ccode:"226" , iso: "BF", currency:"NGN"},
      {name:"BULGARIA" , ccode:"359" , iso: "BG", currency:"NGN"},
      {name:"BAHRAIN" , ccode:"973" , iso: "BH", currency:"NGN"},
      {name:"BURUNDI" , ccode:"257" , iso: "BI", currency:"NGN"},
      {name:"BENIN" , ccode:"229" , iso: "BJ", currency:"NGN"},
      {name:"SAINT BARTHELEMY" , ccode:"590" , iso: "BL", currency:"NGN"},
      {name:"BERMUDA" , ccode:"1441" , iso: "BM", currency:"NGN"},
      {name:"BRUNEI DARUSSALAM" , ccode:"673" , iso: "BN", currency:"NGN"},
      {name:"BOLIVIA" , ccode:"591" , iso: "BO", currency:"NGN"},
      {name:"BRAZIL" , ccode:"55" , iso: "BR", currency:"NGN"},
      {name:"BAHAMAS" , ccode:"1242" , iso: "BS", currency:"NGN"},
      {name:"BHUTAN" , ccode:"975" , iso: "BT", currency:"NGN"},
      {name:"BOTSWANA" , ccode:"267" , iso: "BW", currency:"NGN"},
      {name:"BELARUS" , ccode:"375" , iso: "BY" , currency:"NGN"},
      {name:"BELIZE" , ccode:"501" , iso: "BZ", currency:"NGN"},
      {name:"CANADA" , ccode:"1" , iso: "CA", currency:"NGN"},
      {name:"COCOS (KEELING) ISLANDS)" , ccode:"61" , iso: "CC", currency:"NGN"},
      {name:"CONGO, THE DEMOCRATIC REPUBLIC OF THE" , ccode:"243" , iso: "CD", currency:"NGN"},
      {name:"CENTRAL AFRICAN REPUBLIC" , ccode:"236" , iso: "CF", currency:"NGN"},
      {name:"CONGO" , ccode:"242" , iso: "CG", currency:"NGN"},
      {name:"SWITZERLAND" , ccode:"41" , iso: "CH", currency:"NGN"},
      {name:"COTE D IVOIRE" , ccode:"225" , iso: "CI", currency:"NGN"},
      {name:"COOK ISLANDS" , ccode:"682" , iso: "CK", currency:"NGN"},
      {name:"CHILE" , ccode:"56" , iso: "CL", currency:"NGN"},
      {name:"CAMEROON" , ccode:"237" , iso: "CM", currency:"NGN"},
      {name:"CHINA" , ccode:"86" , iso: "CN", currency:"NGN"},
      {name:"COLOMBIA" , ccode:"57" , iso: "CO", currency:"NGN"},
      {name:"COSTA RICA" , ccode:"506" , iso: "CR", currency:"NGN"},
      {name:"CUBA" , ccode:"53" , iso: "CU", currency:"NGN"},
      {name:"CAPE VERDE" , ccode:"238" , iso: "CV", currency:"NGN"},
      {name:"CHRISTMAS ISLAND" , ccode:"61" , iso: "CX", currency:"NGN"},
      {name:"CYPRUS" , ccode:"357" , iso: "CY", currency:"NGN"},
      {name:"CZECH REPUBLIC" , ccode:"420" , iso: "CZ", currency:"NGN"},
      {name:"GERMANY" , ccode:"49" , iso: "DE", currency:"NGN"},
      {name:"DJIBOUTI" , ccode:"253" , iso: "DJ", currency:"NGN"},
      {name:"DENMARK" , ccode:"45" , iso: "DK", currency:"NGN"},
      {name:"DOMINICA" , ccode:"1767" , iso: "DM", currency:"NGN"},
      {name:"DOMINICAN REPUBLIC" , ccode:"1809" , iso: "DO", currency:"NGN"},
      {name:"ALGERIA" , ccode:"213" , iso: "DZ", currency:"NGN"},
      {name:"ECUADOR" , ccode:"593" , iso: "EC", currency:"NGN"},
      {name:"ESTONIA" , ccode:"372" , iso: "EE", currency:"NGN"},
      {name:"EGYPT" , ccode:"20" , iso: "EG", currency:"NGN"},
      {name:"ERITREA" , ccode:"291" , iso: "ER", currency:"NGN"},
      {name:"SPAIN" , ccode:"34" , iso: "ES", currency:"NGN"},
      {name:"ETHIOPIA" , ccode:"251" , iso: "ET", currency:"NGN"},
      {name:"FINLAND" , ccode:"358" , iso: "FI", currency:"NGN"},
      {name:"FIJI" , ccode:"679" , iso: "FJ", currency:"NGN"},
      {name:"FALKLAND ISLANDS (MALVINAS)" , ccode:"500" , iso: "FK", currency:"NGN"},
      {name:"MICRONESIA, FEDERATED STATES OF" , ccode:"691" , iso: "FM", currency:"NGN"},
      {name:"FAROE ISLANDS" , ccode:"298" , iso: "FO", currency:"NGN"},
      {name:"FRANCE" , ccode:"33" , iso: "FR", currency:"NGN"},
      {name:"GABON" , ccode:"241" , iso: "GA", currency:"NGN"},
      {name:"UNITED KINGDOM" , ccode:"44" , iso: "GB", currency:"NGN"},
      {name:"GRENADA" , ccode:"1473" , iso: "GD", currency:"NGN"},
      {name:"GEORGIA" , ccode:"995" , iso: "GE", currency:"NGN"},
      {name:"GHANA" , ccode:"233" , iso: "GH", currency:"NGN"},
      {name:"GIBRALTAR" , ccode:"350" , iso: "GI", currency:"NGN"},
      {name:"GREENLAND" , ccode:"299" , iso: "GL", currency:"NGN"},
      {name:"GAMBIA" , ccode:"220" , iso: "GM", currency:"NGN"},
      {name:"GUINEA" , ccode:"224" , iso: "GN", currency:"NGN"},
      {name:"EQUATORIAL GUINEA" , ccode:"240" , iso: "GQ", currency:"NGN"},
      {name:"GREECE" , ccode:"30" , iso: "GR", currency:"NGN"},
      {name:"GUATEMALA" , ccode:"502" , iso: "GT", currency:"NGN"},
      {name:"GUAM" , ccode:"1671" , iso: "GU", currency:"NGN"},
      {name:"GUINEA-BISSAU" , ccode:"245" , iso: "GW", currency:"NGN"},
      {name:"GUYANA" , ccode:"592" , iso: "GY", currency:"NGN"},
      {name:"HONG KONG" , ccode:"852" , iso: "HK", currency:"NGN"},
      {name:"HONDURAS" , ccode:"504" , iso: "HN", currency:"NGN"},
      {name:"CROATIA" , ccode:"385" , iso: "HR", currency:"NGN"},
      {name:"HAITI" , ccode:"509" , iso: "HT", currency:"NGN"},
      {name:"HUNGARY" , ccode:"36" , iso: "HU", currency:"NGN"},
      {name:"INDONESIA" , ccode:"62" , iso: "ID", currency:"NGN"},
      {name:"IRELAND" , ccode:"353" , iso: "IE", currency:"NGN"},
      {name:"ISRAEL" , ccode:"972" , iso: "IL", currency:"NGN"},
      {name:"ISLE OF MAN" , ccode:"44" , iso: "IM", currency:"NGN"},
      {name:"INDIA" , ccode:"91" , iso: "IN", currency:"INR"},
      {name:"IRAQ" , ccode:"964" , iso: "IQ", currency:"NGN"},
      {name:"IRAN, ISLAMIC REPUBLIC OF" , ccode:"98" , iso: "IR", currency:"NGN"},
      {name:"ICELAND" , ccode:"354" , iso: "IS", currency:"NGN"},
      {name:"ITALY" , ccode:"39" , iso: "IT", currency:"NGN"},
      {name:"JAMAICA" , ccode:"1876" , iso: "JM", currency:"NGN"},
      {name:"JORDAN" , ccode:"962" , iso: "JO", currency:"NGN"},
      {name:"JAPAN" , ccode:"81" , iso: "JP", currency:"NGN"},
      {name:"KENYA" , ccode:"254" , iso: "KE", currency:"NGN"},
      {name:"KYRGYZSTAN" , ccode:"996" , iso: "KG", currency:"NGN"},
      {name:"CAMBODIA" , ccode:"855" , iso: "KH", currency:"NGN"},
      {name:"KIRIBATI" , ccode:"686" , iso: "KI", currency:"NGN"},
      {name:"COMOROS" , ccode:"269" , iso: "KM", currency:"NGN"},
      {name:"SAINT KITTS AND NEVIS" , ccode:"1869" , iso: "KN", currency:"NGN"},
      {name:"KOREA DEMOCRATIC PEOPLES REPUBLIC OF" , ccode:"850" , iso: "KP", currency:"NGN"},
      {name:"KOREA REPUBLIC OF" , ccode:"82" , iso: "KR", currency:"NGN"},
      {name:"KUWAIT" , ccode:"965" , iso: "KW", currency:"NGN"},
      {name:"CAYMAN ISLANDS" , ccode:"1345" , iso: "KY", currency:"NGN"},
      {name:"KAZAKSTAN" , ccode:"7" , iso: "KZ", currency:"NGN"},
      {name:"LAO PEOPLES DEMOCRATIC REPUBLIC" , ccode:"856" , iso: "LA", currency:"NGN"},
      {name:"LEBANON" , ccode:"961" , iso: "LB", currency:"NGN"},
      {name:"SAINT LUCIA" , ccode:"1758" , iso: "LC", currency:"NGN"},
      {name:"LIECHTENSTEIN" , ccode:"423" , iso: "LI", currency:"NGN"},
      {name:"SRI LANKA" , ccode:"94" , iso: "LK", currency:"NGN"},
      {name:"LIBERIA" , ccode:"231" , iso: "LR", currency:"NGN"},
      {name:"LESOTHO" , ccode:"266" , iso: "LS", currency:"NGN"},
      {name:"LITHUANIA" , ccode:"370" , iso: "LT", currency:"NGN"},
      {name:"LUXEMBOURG" , ccode:"352" , iso: "LU", currency:"NGN"},
      {name:"LATVIA" , ccode:"371" , iso: "LV", currency:"NGN"},
      {name:"LIBYAN ARAB JAMAHIRIYA" , ccode:"218" , iso: "LY", currency:"NGN"},
      {name:"MOROCCO" , ccode:"212" , iso: "MA", currency:"NGN"},
      {name:"MONACO" , ccode:"377" , iso: "MC", currency:"NGN"},
      {name:"MOLDOVA, REPUBLIC OF" , ccode:"373" , iso: "MD", currency:"NGN"},
      {name:"MONTENEGRO" , ccode:"382" , iso: "ME", currency:"NGN"},
      {name:"SAINT MARTIN" , ccode:"1599" , iso: "MF", currency:"NGN"},
      {name:"MADAGASCAR" , ccode:"261" , iso: "MG", currency:"NGN"},
      {name:"MARSHALL ISLANDS" , ccode:"692" , iso: "MH", currency:"NGN"},
      {name:"MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF" , ccode:"389" , iso: "MK", currency:"NGN"},
      {name:"MALI" , ccode:"223" , iso: "ML", currency:"NGN"},
      {name:"MYANMAR" , ccode:"95" , iso: "MM", currency:"NGN"},
      {name:"MONGOLIA " , ccode:"976" , iso: "MN", currency:"NGN"},
      {name:"MACAU" , ccode:"853" , iso: "MO", currency:"NGN"},
      {name:"NORTHERN MARIANA ISLANDS" , ccode:"1670" , iso: "MP", currency:"NGN"},
      {name:"MAURITANIA" , ccode:"222" , iso: "MR", currency:"NGN"},
      {name:"MONTSERRAT" , ccode:"1664" , iso: "MS", currency:"NGN"},
      {name:"MALTA" , ccode:"356" , iso: "MT", currency:"NGN"},
      {name:"MAURITIUS" , ccode:"230" , iso: "MU", currency:"NGN"},
      {name:"MALDIVES" , ccode:"960" , iso: "MV", currency:"NGN"},
      {name:"MALAWI" , ccode:"265" , iso: "MW", currency:"NGN"},
      {name:"MEXICO " , ccode:"52" , iso: "MX", currency:"NGN"},
      {name:"MALAYSIA" , ccode:"60" , iso: "MY", currency:"NGN"},
      {name:"MOZAMBIQUE" , ccode:"258" , iso: "MZ", currency:"NGN"},
      {name:"NAMIBIA" , ccode:"264" , iso: "NA", currency:"NGN"},
      {name:"NEW CALEDONIA" , ccode:"687" , iso: "NC", currency:"NGN"},
      {name:"NIGER" , ccode:"227" , iso: "NE", currency:"NGN"},
      
      {name:"NICARAGUA" , ccode:"505" , iso: "NI", currency:"NGN"},
      {name:"NETHERLANDS" , ccode:"31" , iso: "NL", currency:"NGN"},
      {name:"NORWAY" , ccode:"47" , iso: "NO", currency:"NGN"},
      {name:"NEPAL" , ccode:"977" , iso: "NP", currency:"NGN"},
      {name:"NAURU" , ccode:"674" , iso: "NR", currency:"NGN"},
      {name:"NIUE" , ccode:"683" , iso: "NU", currency:"NGN"},
      {name:"NEW ZEALAND" , ccode:"64" , iso: "NZ", currency:"NGN"},
      {name:"OMAN" , ccode:"968" , iso: "OM", currency:"NGN"},
      {name:"PANAMA" , ccode:"507" , iso: "PA", currency:"NGN"},
      {name:"PERU" , ccode:"51" , iso: "PE", currency:"NGN"},
      {name:"FRENCH POLYNESIA" , ccode:"689" , iso: "PF", currency:"NGN"},
      {name:"PAPUA NEW GUINEA" , ccode:"675" , iso: "PG", currency:"NGN"},
      {name:"PHILIPPINES" , ccode:"63" , iso: "PH", currency:"NGN"},
      {name:"PAKISTAN" , ccode:"92" , iso: "PK", currency:"NGN"},
      {name:"POLAND" , ccode:"48" , iso: "PL", currency:"NGN"},
      {name:"SAINT PIERRE AND MIQUELON" , ccode:"508" , iso: "PM", currency:"NGN"},
      {name:"PITCAIRN" , ccode:"870" , iso: "PN", currency:"NGN"},
      {name:"PUERTO RICO" , ccode:"1" , iso: "PR", currency:"NGN"},
      {name:"PORTUGAL" , ccode:"351" , iso: "PT", currency:"NGN"},
      {name:"PALAU" , ccode:"680" , iso: "PW", currency:"NGN"},
      {name:"PARAGUAY" , ccode:"595" , iso: "PY", currency:"NGN"},
      {name:"QATAR" , ccode:"974" , iso: "QA", currency:"NGN"},
      {name:"ROMANIA" , ccode:"40" , iso: "RO", currency:"NGN"},
      {name:"SERBIA" , ccode:"381" , iso: "RS", currency:"NGN"},
      {name:"RUSSIAN FEDERATION" , ccode:"7" , iso: "RU", currency:"NGN"},
      {name:"RWANDA" , ccode:"250" , iso: "RW", currency:"NGN"},
      {name:"SAUDI ARABIA" , ccode:"966" , iso: "SA", currency:"NGN"},
      {name:"SOLOMON ISLANDS" , ccode:"677" , iso: "SB", currency:"NGN"},
      {name:"SEYCHELLES" , ccode:"248" , iso: "SC", currency:"NGN"},
      {name:"SUDAN" , ccode:"249" , iso: "SD", currency:"NGN"},
      {name:"SWEDEN" , ccode:"46" , iso: "SE", currency:"NGN"},
      {name:"SINGAPORE" , ccode:"65" , iso: "SG", currency:"NGN"},
      {name:"SAINT HELENA" , ccode:"290", iso: "SH" , currency:"NGN"},
      {name:"SLOVENIA" , ccode:"386" , iso: "SI", currency:"NGN"},
      {name:"SLOVAKIA" , ccode:"421" , iso: "SK", currency:"NGN"},
      {name:"SIERRA LEONE" , ccode:"232" , iso: "SL", currency:"NGN"},
      {name:"SAN MARINO" , ccode:"378" , iso: "SM", currency:"NGN"},
      {name:"SENEGAL" , ccode:"221" , iso: "SN", currency:"NGN"},
      {name:"SOMALIA" , ccode:"252" , iso: "SO", currency:"NGN"},
      {name:"SURINAME" , ccode:"597" , iso: "SR", currency:"NGN"},
      {name:"SAO TOME AND PRINCIPE" , ccode:"239" , iso: "ST", currency:"NGN"},
      {name:"EL SALVADOR" , ccode:"503" , iso: "SV", currency:"NGN"},
      {name:"SYRIAN ARAB REPUBLIC" , ccode:"963" , iso: "SY", currency:"NGN"},
      {name:"SWAZILAND" , ccode:"268" , iso: "SZ", currency:"NGN"},
      {name:"TURKS AND CAICOS ISLANDS" , ccode:"1649" , iso: "TC", currency:"NGN"},
      {name:"CHAD" , ccode:"235" , iso: "TD", currency:"NGN"},
      {name:"TOGO" , ccode:"228" , iso: "TG", currency:"NGN"},
      {name:"THAILAND" , ccode:"66" , iso: "TH", currency:"NGN"},
      {name:"TAJIKISTAN" , ccode:"992" , iso: "TJ", currency:"NGN"},
      {name:"TOKELAU" , ccode:"690" , iso: "TK", currency:"NGN"},
      {name:"TIMOR-LESTE" , ccode:"670" , iso: "TL", currency:"NGN"},
      {name:"TURKMENISTAN" , ccode:"993" , iso: "TM", currency:"NGN"},
      {name:"TUNISIA" , ccode:"216" , iso: "TN", currency:"NGN"},
      {name:"TONGA" , ccode:"676" , iso: "TO", currency:"NGN"},
      {name:"TURKEY" , ccode:"90" , iso: "TR", currency:"NGN"},
      {name:"TRINIDAD AND TOBAGO" , ccode:"1868" , iso: "TT", currency:"NGN"},
      {name:"TUVALU" , ccode:"688" , iso: "TV", currency:"NGN"},
      {name:"TAIWAN, PROVINCE OF CHINA" , ccode:"886" , iso: "TW", currency:"NGN"},
      {name:"TANZANIA, UNITED REPUBLIC OF" , ccode:"255" , iso: "TZ", currency:"NGN"},
      {name:"UKRAINE" , ccode:"380" , iso: "UA", currency:"NGN"},
      {name:"UGANDA" , ccode:"256" , iso: "UG", currency:"NGN"},
      {name:"UNITED STATES" , ccode:"1" , iso: "US", currency:"USD"},
      {name:"URUGUAY" , ccode:"598" , iso: "UY", currency:"NGN"},
      {name:"UZBEKISTAN" , ccode:"998" , iso: "UZ", currency:"NGN"},
      {name:"HOLY SEE (VATICAN CITY STATE)" , ccode:"39" , iso: "VA", currency:"NGN"},
      {name:"SAINT VINCENT AND THE GRENADINES" , ccode:"1784" , iso: "VC", currency:"NGN"},
      {name:"VENEZUELA" , ccode:"58" , iso: "VE", currency:"NGN"},
      {name:"VIRGIN ISLANDS, BRITISH" , ccode:"1284" , iso: "VG", currency:"NGN"},
      {name:"VIRGIN ISLANDS, U.S." , ccode:"1340" , iso: "VI", currency:"NGN"},
      {name:"VIET NAM" , ccode:"84" , iso: "VN", currency:"NGN"},
      {name:"VANUATU" , ccode:"678" , iso: "VU", currency:"NGN"},
      {name:"WALLIS AND FUTUNA" , ccode:"681" , iso: "WF", currency:"NGN"},
      {name:"SAMOA" , ccode:"685" , iso: "WS", currency:"NGN"},
      {name:"KOSOVO" , ccode:"381" , iso: "XK", currency:"NGN"},
      {name:"YEMEN" , ccode:"967" , iso: "YE", currency:"NGN"},
      {name:"MAYOTTE" , ccode:"262" , iso: "YT", currency:"NGN"},
      {name:"SOUTH AFRICA" , ccode:"27" , iso: "ZA", currency:"NGN"},
      {name:"ZAMBIA" , ccode:"260" , iso: "ZM", currency:"NGN"},
      {name:"ZIMBABWE" , ccode:"263" , iso: "ZW", currency:"NGN"}
  ],


PAYMENT_FREQUENCY_DAILY:"daily",
PAYMENT_FREQUENCY_WEEKLY:"weekly",
PAYMENT_FREQUENCY_MONTHLY:"monthly",
PAYMENT_FREQUENCY_BI_WEEKLY:"bi-weekly",

COMMISSION_WALLET_TRANSFER : "transfer_internal",
COMMISSION_NUMBER_PAY : "number_pay",
COMMISSION_AGENT_PAY : "agent_pay",
COMMISSION_QUICK_PAY : "quick_pay",
COMMISSION_NAIRA_PAY : "naira_pay",
COMMISSION_TRANSFER_TO : "transferto",
COMMISSION_PAYSTACK_FUND_TRANSFER : "paystack_fund_transfer",
COMMISSION_JFNX_FUND_TRANSFER : "jfnx_fund_transfer",

OTP_WAITING_TIME:60,

METHOD_USER_ADD:'add_to_group',
METHOD_USER_ACCEPTED:'user_accepted',
METHOD_USER_DECLINED:'user_declined',
METHOD_USER_REQUESTED:'user_requested',
 
METHOD_GET:'GET',
METHOD_POST:'POST',

// BASE_URL:"http://52.168.138.199:3001/",
// BASE_URL:"http://api.mnaira.app:3001/",
BASE_URL:"https://api.mnaira.app:8080/",
BASE_URL_1:"https://api.beeptool.com:8080/",
// BASE_URL:"http://67.203.1.226:3001/",

// AVATAR_REPLACE_CHARACTER: "####",
// AVATAR_URL: BASE_URL + "files/"+ Strings.AVATAR_REPLACE_CHARACTER +"/avatar_raw.jpg",

SIGN_UP_URL:"accounts/signUp",
UPLOAD_CONTACTS_URL:"profiles/upload",
GET_CONTACTS_URL:"profiles/all",
UPLOAD_PROFILE_URL:"profiles/add_to_profile",
UPLOAD_PROFILE_PIC_URL:"profiles/upload_avatar",
GET_PROFILE_URL:"profiles/",  
UPLOAD_TOKEN_URL:"utils/PUSH/subscribe",
USER_TO_USER_TRANSFER_URL:"payments/",
USER_PAYMENT_LIST_URL:"payments/",
GET_USER_BALANCE:"accounts/",
ADD_FUNDS_URL:"payments/",
GET_COMMISSION_URL :"payments/general/transaction_comission",
CHECK_COMMISSION_URL :"check_commissions",
GET_PAYMENT_AMOUNT:"payments/pay_amounts",
INVITE_FRIENDS_URL:"utils/sendSMSToMany",
GET_TOP_UP_PRODUCTS:"payments/mobile_topup/products/",
TOPUP_PLAN:"payments/",
GET_LUMP_SUM_AMOUNT:"ajo/get_lump_amounts",

GET_BILL_CATEGORIES:"payments/quickteller/getCategories",
GET_BILLERS:"payments/quickteller/getBillersInCategory/",
GET_PAYMENT_ITEMS:"payments/quickteller/getPaymentItems/",
MAKE_BILL_PAYMENT:"payments/quickteller/billers/pay_item",

GET_BANK_ACCOUNTS:"payments/paystack/banks/fetch",
GET_BANK_ACCOUNTS_OUTSIDE:"payments/banks/fetch",
GET_ACCOUNT_LOOK_UP:"payments/banks/account_lookup",
CREATE_BANK_RECIPIENT:"payments/paystack/create_recipient",
MAKE_BANK_TRANSFER:"payments/paystack/transfer",
MAKE_OUTSIDE_BANK_TRANSFER:"payments/banks/send_transfer",
GET_FX_RATE:"payments/banks/fx_converter",
GET_RECIPIENT:"payments/paystack/get_recipients?",
UPLOAD_SIGNATURE:"profiles/upload_file",
BECOME_AGENT:"agents/add",
NEAREST_AGENT:"agents/get_nearest",
SEND_CASH:"agents/send_cash",
GET_USER_TRANSACTIONS:"agents/transactions",
GET_AGENT_TRANSACTIONS:"agents/transactions/agent",
GET_PAY_TO_NUMBER_TRANSACTIONS:"get_transactions",
ACCEPT_TRANSACTION:"agents/accept_transaction",
CASH_OUT_TRANSACTION:"agents/cash_out_transaction",
DECLINE_TRANSACTION:"agents/decline_transaction",
CANCEL_TRANSACTION:"agents/cancel_transaction",
CHANGE_AGENT_TRANSACTION:"agents/change_agent_transaction",
UPLOAD_AGENT_FILES:"files/upload_file",
PAY_TO_NUMBER:"pay_number",
USE_TOKEN:"use_token",


CHECK_SCAN_TRANSACTION_ID:'payments/naira_pay_no_trans/',

QUICK_CASH_OUT:"quick_pay",
QUICK_PAY_CONFIRM:"quick_pay_confirm",
QUICK_PAY_CANCEL:"quick_pay_cancel",
QUICK_PAY_TRANSACTIONS:"quick_pay_get_transaction",
// GET_AVATAR:"files/919016066530/avatar_raw.jpg",

CREATE_GROUP:"events",
// ACCEPT_GROUP_INVITE:"events",
// DECLINE_GROUP_INVITE:"events",

ADD_BANK_ACCOUNT:"accounts/bank_accounts",

GET_CASH_LIMITS:'check_limits',

AGENT_FILE_TYPE_ID:"id_scan",
AGENT_FILE_TYPE_ADDRESS_PROOF:"proof_address",
AGENT_FILE_TYPE_PHOTO:"photo",

GROUP_INVITATION_ACCEPT:"active",
GROUP_INVITATION_DECLINE:"declined",

AGENT_REQUEST_STATUS_PENDING:"awaiting_accept",
AGENT_REQUEST_STATUS_DECLINED:"declined_by_agent",
AGENT_REQUEST_STATUS_ACCEPTED:"accepted_by_agent",
AGENT_REQUEST_STATUS_CANCELLED:"canceled",
AGENT_REQUEST_STATUS_COMPLETED:"completed",

};
export default Strings;
